#!/bin/bash
set -e

if [ $# -eq 0 -o "$1" == "-h" -o "$1" == "--help" ];then
    echo "Usage :" 
    echo "./pdsframe --config CONFIG_FILE --action {start|stop|status} [--front] "
    exit 1
fi

DIR="/opt/smartmgr/pdsframe"
python "$DIR/core/main.pyc" $*
